
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://192.168.219.100/ohho
    driverClassName: org.mariadb.jdbc.Driver
    username: jiheon2234
    password: '0000'
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop


mybatis:
  mapper-locations : classpath:mybatis/mapper/mariadb/**.xml
  type-handlers-package: com.jiheon.demo.mapper.typehandler
  type-aliases-package: com.jiheon.demo.model
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100

